- Makefile
- docs/format.html
- icemulti/.gitignore
- icemulti/Makefile
- icemulti/icemulti.cc
Hi.
I created a tool to build multiboot (cold/warm boot) images for iCE40.  At first I pondered adding this functionality to icepack, but on second thought it didn't seem like a very good fit so I just made a
separate tool instead.
Feel free to include it in icestorm.
> "Advanced SPI flash" (multiboot) tool

- icepack/icepack.cc
There are 3 changes at least needed to get icepack.cc to compile and work with VS2013
> fixed for VS2013

- examples/hx8kboard/Makefile
- examples/icestick/Makefile
Just added a few variables at the beginning of the makefiles so one does not have to rewrite everything for initial projects. :)
> [examples] Made the example Makefiles easier to reuse.

- docs/notes_osx.md
The toolchain should be easy to install on OSX platforms. I detail a few troubleshooting items found that might help others.
> OSX Install notes after workshop 

- icepack/icepack.cc
- icepll/icepll.cc
- icetime/icetime.cc
This branch contains some commits from the debian packaging effort.  It only fixes spelling mistakes in user-visible messages.
> fix some spelling mistakes in user-visible messages

- config.mk
> Make clang optional

- icebram/icebram.cc
Hi.  Here's a fix for some of the stuff mentioned in #56.  Sorry it took a while.
It adds support for the following in the input hexfiles:
* Horizontal whitespace (space, tab, cr)
* More than one word on the same line
* Less than one word on the same line (i.e. empty lines)
* Embedded underscores (_) in the words
* x and z nibbles (interpreted as zero)
In addition, it allows for the to_hexfile to be shorter than the
from_hexfile, padding with zeroes as needed.
I did not add support for comments or addresses, since that would have required a larger restructuring of the code.
Note that a sequence containing only underscores (___) will be silently ignored, even though it would probably count as a syntax error in $readmemh...
> Improve input parsing of icebram

- icepll/icepll.cc
e.g. to do be able to do
<pre>
$ icepll -i 12 -o 90 -q -f pll_90mhz.v
</pre>
> icepll: added options to save PLL config as Verilog and for quiet output

- icepack/icepack.cc
Could you please consider merging my added code supporting the iCE40 LP384 in icepack into main branch?
That's just a start, I'd really like to have full LP384 chipdb support in IceStorm in the end.
> LP384 support in icepack

- iceprog/iceprog.c
> Remove use of err.h

- icebox/icebox_html.py
Unsure about what IO tiles should be enabled, so all are enabled.
> Add LP384 support to icebox_html

- icepack/icepack.cc
Per [discussion on Twitter](https://twitter.com/oe1cxw/status/946468223574331395). My changes as-is work, but PR is incomplete; I need to update documentation. Before that however, I would like to discuss/massage the PR so it's more to your liking if necessary.
In particular, I've confirmed w/ test bitstreams what I [thought was happening](https://twitter.com/cr1901/status/946912271720177664):
* Opcode 0x09 expects a bitmask, rather than the values `0`, `16`, and `32`.
* Bit 0- Set to disable final SPI deep sleep. This is necessary on designs which need the flash/don't expect the flash to be powered down before the user gains control. No equivalent in the ASCII format, so I [improvised](https://github.com/cr1901/icestorm/commit/c093efc01558a56a0ab2ee35d0c896ce3f692bbe). I would call the …
> Add option to `icepack` to disable SPI Deep Power-Down command in bitstream.

- icepack/icepack.cc
I don't know if I'll ever find time to add full iCE40 Ultra support to icestorm, but I thought I'd start the job for anyone wishing to take this on by adding the capability to pack/unpack bitstreams for these parts.
It is interesting to note that, although referred to as "u4k" here, the silicon appears identical for the 1k, 2k and 4k parts.
This hasn't been thoroughly tested yet, and I don't have any suitable hardware so I can't actually confirm the packed bitstreams work (but they're sufficiently similar to the original bitstream from iCEcube I'll assume they do.)
> Add iCE40 Ultra (ice5lp) support to icepack

- icetime/icetime.cc
This prints warning message but allows timing analysis to continue (whereas previously it would subsequently fail) when unsupported cell types are encountered in the 5k device. This is primarily an interim until these cells are worked out.
> Properly ignore unsupported cell types

- docs/format.html
- docs/logic_tile.html
Signed-off-by: John McMaster <johndmcmaster@gmail.com>
> docs: spelling/grammer

- icefuzz/icecube.sh
- icepack/icepack.cc
This PR adds support for LM-series chips in iccepack and icecube.sh.
> LM4K support in icepack and icecube.sh

- icebox/icebox_hlc2asc.py
> Support both `abc/123` and `123` forms of specifying tracks.

- icebox/icebox_vlog.py
The lutff_X/lout is a driver signal.
> icebox: Fix driver detection for LUT cascade.

- icebram/icebram.cc
I want the .hex files to be generated by a makefile, but I also want them to always have the same contents on each run.
Tom
> icebram: add option to specify seed for repeatable outcomes.

- icebox/icebox_hlc2asc.py
Current code fails with the following;
```
Parse error in line 94:
span4_y3_g15_6 -> local_g0_3 -> D_OUT_0
```
> icebox: Fix issue introduced by f7e9fec63a3f88bee8c27e858da319ea03d68d14

- examples/iceblink/README
The example doesn't work out of the box with the iCEblink40-lp1k board.
> Update README to be clearer

- icebox/icebox_hlc2asc.py
Previously the 1k global networks were hard coded. This now uses the
values from the given part.
> hlc: Use glb_network for current device.

- docs/index.html
To make things easier I have added the NextPNR instructions to docs. This way I can provide users with one link for the installation instructions instead of two. ;)
> Added NextPNR deps and install instructions to docs.

- docs/index.html
Signed-off-by: David Shah <dave@ds0.me>
> docs: Add new Eigen3 dependency

- icepll/icepll.cc
stdout is useful for chaining tools on the command line. (unix style)
This commit adds support for writing the Verilog output of icepll to stdout.
That way the user does not have to use temporary files, if the output is processed further.
> icepll: Add support for writing output data to stdout

- Makefile
- config.mk
> Make iceprog optional

- iceprog/iceprog.c
This allows us to flash binaries at offsets that are smaller multiples.
We should still consider this functionality as a stepping stone to a intelligent erase function that chooses the correct sizes of blocks to erase only the section of the flash that is necessary while using the biggest block size possible.
> Added an option to choose the erase block size.

- icepll/icepll.cc
This patch adds support for icepll to try multiple input frequencies to find the best crystal for the desired output frequency.
The values tested comes either from a specified file using-B, or from a default set of frequencies from Mousers "normally stocked" crystal oscillators.
> The rationale for this is that I wanted to get as close as possible to the 25.175 MHz for the VGA pixel clock using some easily available crystal oscillator frequency. It looks like a lot of changes to the original source, but most of it is just refactoring of the calculation code to its own function.
> icepll: Add iteration over list of frequencies for best solution

- icebox/Makefile
Fixes https://github.com/cliffordwolf/icestorm/pull/248#discussion_r406850339
> icebox: fix missing DESTDIR for icebox_chipdb

- icebox/Makefile
$(DESTDIR) in vlog script causes error when installed
> Make sure that scripts find files on final install

- iceprog/iceprog.c
Signed-off-by: Sylvain Munaut <tnt@246tNt.com>
> iceprog: Add option to keep flash powered up

- icebram/icebram.cc
I actually did not understand the logic icebram was following when submitting #260, as I've been informed in https://github.com/YosysHQ/prjtrellis/pull/145. I rewrote the logic of icebram to match the logic of ecpbram and explained what it does for the next person.
> Fix icebram

- icebox/icebox_vlog.py
Since ce1d811, SHIFTREG_DIV_MODE is now 2 bits for the up5k
> Fix icebox_vlog for up5k

- icetime/Makefile
- icetime/icetime.cc
This one also include a fix to prevent regeneration of timing files when not needed
> Support rest of parts by icetime

- README
The README refers to the old web site that no longer exists.
> Update URL for web site.

- icetime/icetime.cc
This is required to avoid falsely reported combinational loops with YosysHQ/nextpnr#966, which allows an unrelated driving LUT2 and SB_CARRY to be packed into the same LC, with the inputs used for the carry being don't cares in the LUT function.
> icetime: Ignore false paths through LUTs based on function

- iceprog/iceprog.c
Theses are a few patch I've been using locally for the past couple of years ...
Feel free to pick what interest you if not everything is suitable.
> Misc improvements to iceprog

- icepll/icepll.cc
When a clock is applied to a dedicated clock pin, ```SB_PLL40_CORE``` is no longer the correct primitive to use.
Also the name of the clock input must be ```PACKAGEPIN``` (rather than ```REFERENCECLK```)
This switch allows the easy use of ```icepll``` with hardware that connects clock signals to dedicated clock signal pins (like the Lattice iCE40 UltraPlus Breakout Board, iCEBreaker, iCEBreaker Bitsy, Fomu etc.)
(Addresses Issue https://github.com/YosysHQ/icestorm/issues/190)
> Add an option (-p) to icepll to force use of SB_PLL40_PAD

- icebram/icebram.cc
Fixes #301 
I know it's a large diff, but it's pretty much a rewrite since the old structure of one giant main() function was becoming unwieldy.
icebram used to parse each .ram_data line one at a time but now it needs to load the whole memory. It also needs to know the READ_MODE (and so parse the ram config tile).
> icebram: Complete rewrite to cleanup and make it work

- docs/ram_tile.html
See https://github.com/YosysHQ/nextpnr/pull/1128
> Update BRAM NegClk info based on latest testing

- docs/source/overview.rst
Guix provides recent versions of icestorm, nextpnr and yosys tools.
> install instructions with guix
