YosysHQ/icestorm

Makefile, icebox/Makefile, icefuzz/Makefile, icemulti/Makefile, icepack/Makefile, iceprog/Makefile
Hola!
This PR gives users the ability to build icestorm on machines that have differently named python interpreters (and also c++ compilers).
This for example, allows for building on OpenBSD:
```
env PYTHON=python2.7 CXX=eg++ gmake
```
I also added includes and libs from /usr/local as this is where libftdi and friends are located on OpenBSD.
I was also wondering about the licensing of this project. It doesn't seem to contain any license information. Is that something you will add later down the line?
***edit***: Found a [reference](https://hackaday.io/project/6636-iced-an-arduino-style-board-with-ice-fpga) to it being MIT, but clarification would still be awesome :D
=> Add entry points for PYTHON and CXX

icebox/Makefile
Hi! I am testing Icestorm debian packaging for launchpad and I found a bug in the "icestorm/Makefile".
I have detected it while running:
$ fakeroot debian/rules binary-arch
Regards!
=> Icebox Makefile install section fixed

iceprog/iceprog.c
Having pipe support allows iceprog to be integrated with other tools.
For example, iCE40 bit-streams are often highly compressible. Having pipe support allows the bit-stream to be piped to/from compression tools. For example:
```
iceprog -d i:0x0403:0x6010 -r - | pv -cN iceprog | xz > bistream.fw.xz
```
Here `pv` displays an attractive progress display, as the data is compressed by `xz`.
=> Iceprog pipe

docs/index.html
This adds installation instructions for Archlinux to the website.
Initially I was planning on releasing Archlinux packages myself, but someone was faster. It's really great that making Archlinux packages is so easy!
=> Add installation instruction for Archlinux to the website

icetime/Makefile, icetime/icetime.cc
Icetime was hardcoding the path to chipdb as /usr/local/share causing
icetime to not find the chip db on Arch Linux where the prefix is just
/usr/share.
With this commit the PREFIX is passed as a preprocessor define and used
in icetime.cc to create the correct path. I don't know what the
canonical way of dealing with this is, but this was the least intrusive
way I could think of to get this fixed.
This resolves https://github.com/cliffordwolf/icestorm/issues/24
=> icetime: fixed chipdb path issue for Arch Linux

config.mk, examples/iceblink/Makefile, examples/iceblink/README, examples/iceblink/example.v, examples/iceblink/iceblink.pcf
-Take the install prefix from environment. I hope icestorm, arachne-pnr and yosys could all be installed to $PREFIX directory without Makefile/config.mk modifications.
-Adapt the example program to the iceblink board.
=> Two small improvements.

iceprog/iceprog.c
This changes iceprog so that it'll open binary files in binary mode, this means that on windows `\n` isn't substituted with `\r\n` and vice versa on reads and writes.
=> Fix iceprog on Windows opening binary in text mode

iceprog/Makefile
This change gives priority to libftdi1-dev over libftdi-dev in the case that both are installed.
=> Give priority to libftdi1 over libftdi

icetime/icetime.cc
This commit allows to use '~' as the home directory in the icetime PREFIX for WIN32.
Based on https://hg.python.org/cpython/file/v2.7.3/Lib/ntpath.py#l275 source code.
=> icetime: support PREFIX expansion for win32

iceprog/Makefile
Fix to enable a clean build on Mac OS X.
iceprog would fail to compile as it could not find the header ftdi.h.
The fix will check to see if you are compiling on Mac OS X and set the correct LDLIBS and CFLAGS for Mac OS X.
This attempts to detect the correct version of the FTDI headers and sets the correct CFLAGS for the version of the FTDI headers installed.
This is a first pass and has been tested. It also only applies if uname -s is equal to Darwin. I have tested to ensure this still compiles correctly on Linux.
brew install libftdi is the common way to install libfdti on Mac OS X. #
=> Adam D. Horden iceprog makefile osx fix.

config.mk, icetime/Makefile, icetime/icetime.cc
It determines the subdir name
used in $(PREFIX)/share/ to install the chip database. This provides a
mechanism to choose a directory different than icebox (default).
I.e. fpga-icestorm/chipdb for Debian.
=> Added a new config variable CHIPDB_SUBDIR.

config.mk
Please see https://github.com/udif/cae-win-tools
I have forked 3 repositories only due to Win32 cross compile issues (icestorm, yosis, icarus), and if this pull request is accepted I could remove the icestorm fork.
=> Fix for Win32 builds

iceprog/iceprog.c
The timer latency affects iceprog performance. A value of 16 makes it 5 times slower.
Old kernels have the "low_latency" enabled for this module, so we don't need it.
The cost is 1 kHz interrupts while the device is opened.
New kernel versions are setting more conservative value (16). This relaxes the system (62,5 Hz interrupts) but makes the transfer much slower.
This patch adds a call to ftdi_set_latency_timer to set its value to its optimal (2 => 500 Hz interrupts)
Other projects using SPI on the FTDI also does it. I took the idea from flashrom.
=> Fix latency timer

icetime/icetime.cc
icetime was reading the asc configuration file using a 128-byte line
buffer -- which is usually fine, but can cause it to truncate the names
of nets given in .sym lines if those names are very, very long.
Long net names like this can arise in deeply hierarchical designs,
particularly if there's a code generator involved.
This change expands the line buffer to 1024 bytes.
**Discussion:** this leaves a subtle bug, but its fix will be slightly more invasive, so I wanted to propose this simple fix first and start the discussion.
If icetime encounters a config line longer than this constant minus 1 (here 1023 bytes or more) it will get the latter portion of the line from the *next* fgets call and interpret it as a second line.  If the latter portion happens to begin with, say, `.sym` or …
=> icetime: allow longer lines in input asc files

icepll/icepll.cc
As discussed in issue #83, the range of the DIVF parameter in the
iCE40 PLL Usage Guide is incorrectly listed as being 0-63, when it
should actually be 0-127 when used in the SIMPLE feedback mode. It 
is still restricted to 0-63 in other modes however.
=> Update PLL DIVF range to be [0,127]

config.mk, icebox/Makefile, icebram/Makefile, icemulti/Makefile, icepack/Makefile, icepll/Makefile, iceprog/Makefile, icetime/Makefile
I would like to change the install target so that it can be used on Windows as well as other platforms. This mostly consisted of making the install target honor `$(EXE)`. For the Python scripts in icebox, I added a new `$(PY_EXE)` variable to control the suffix of the Python scripts.
This PR does _not_ delete the existing MXE special case. That has been kept.
This is part of the bikeshed in issue #86.
=> Make install target work for Windows

icebox/icebox.py
Extra bits are read from a file, but they aren't written back.
This patch adds the missing code so they are included in the output.
=> icebox: Preserve extra bits when writing to file

config.mk
This makes it a bit easier to package icestorm for distros, because PREFIX can
be set in one place without having to patch the config.mk in the package build
processes.
The C and C++ standard, optimization and warning level modularization were just
collateral benefit.
=> modularized standard Makefile config

icebox/icebox.py, icepack/icepack.cc
This pull request allows the “warmboot” bit of a configuration image to be preserved in a `.bin` → `.asc` → `.bin` round-trip.
It extends the `.asc` bitstream format in a way that allows it to represent a configuration image with the “warmboot” feature disabled by adding the following two statements to the syntax:
.warmboot disabled
.warmboot enabled
The `.warmboot` statement is only included in the output if the “warmboot” feature is disabled, and the default is to assume that the feature is enabled, so this change should be compatible with existing code.
=> Add support for non-warmboot images

icemulti/icemulti.cc
Since pull request #92 doesn't appear to make any progress, I'm creating a pull request for the next part of the `icemulti` changes without a test suite. This pull request introduces the `getopt` library for parsing command-line arguments, adds some missing error checks (for missing or empty input files and I/O errors) and provides more information with the existing error checks (program and file name).
=> `icemulti' error checks and argument handling

icebox/Makefile, icebox/icebox_asc2hlc.py, icebox/icebox_hlc2asc.py, icebox/tc_logic_xpr.py, icebox/tc_rxlat_netnames.py, icebox/tc_xlat_netnames.py
This pull request contains several fixes for the high-level configuration converters:
- When a .hlc file couldn't be parsed, the offending line and line number are printed
- PLL directives are now parsed correctly
- The names of the special wires in I/O tiles have been fixed
- The converters and tests have been put under the ISC license, as requested in issue #95
=> Fixes to high-level configuration converters

icemulti/icemulti.cc
This is the fourth part of the changes suggested in pull request #90. It causes `icemulti` to include input files listed on the command line only once in the output file, regardless of whether they have been specified explicitly by file name or implicitly using `-p` / as default.
Up to now, `icemulti` included the input files listed on the command line exactly in that order in the output file. The power-on/reset header and, if less than four input files have been specified, the remaining headers point to the input file to be used on power-on/reset (usually the first one).
Normally, the input files are different from each other, so this is not an issue. However, once specifying a default and a power-on/reset input file by its file name rather than index will be implemented, this will cause …
=> icemulti: Re-use images

icebox/icebox.py, icebox/iceboxdb.py, icefuzz/cached_ramb_5k.txt, icefuzz/cached_ramt_5k.txt, icefuzz/tests/colbuf_5k.sh, icefuzz/tests/colbuf_io_5k.sh, icefuzz/tests/colbuf_logic_5k.sh, icefuzz/tests/colbuf_ram_5k.sh, icepack/icepack.cc
This pull request should continue on from the previous UltraPlus development by fixing various functionality, meaning all of the standard ice40 features are now supported on the 5k and have undergone further testing, including running PicoSoC on the 5k.
Still none of the UltraPlus-specific features are supported (except in icepack) but this will be worked on next.
=> Basic support for UltraPlus 5k

iceprog/iceprog.c
This checks 0x0403:0x6014 as well as 0x0403:0x6010, to allow programmers based on the FT232H, such as on the Upduino 2, to be used out of the box.
=> Add out-of-the-box FT232H support (for Upduino 2, etc)

icetime/icetime.cc
It was previously assumed that an underscore in an extra cell net name indicated a numeric value as part of a bus, but this assumption fails for the case `CLKHF_FABRIC`.
=> Fix handling of a port name like CLKHF_FABRIC in icetime

iceprog/iceprog.c
To simplify readability of the iceprog code for the casual passer-by, introduced a bunch of enums and defines containing the FTDI MPSSE engine and SPI Flash commands.
=> Add MPSSE and Flash command definitions 

icebram/icebram.cc, icemulti/icemulti.cc, icepack/icepack.cc, icepll/icepll.cc, icetime/icetime.cc
The first commit makes the following changes:
* Includes config.mk after defining SUBDIRS so that config.mk can override it (so that emscripten doesn't build iceprog)
* Adds an "EMCC" flag to build with emscripten.
* Allows the debug metadata level to be controlled because emscripten does not support `-ggdb`.
* Adds `$(EXE)` in various places
* Adds a hack to the icetime makefile so that it copies over the chipdb files and embeds them into the resulting javascript
The second commit modifies all binaries to mount emscripten's NODEFS on `/x` if the resulting javascript is run under nodejs. This is useful for testing so that the resulting javascript can interact with files on the host filesystem. By default, emscripten-compiled output can only access its in-memory virtual filesystem. It also …
=> Better emscripten support

icebox/icebox_vlog.py
sig values where "1'b0" and "1'b1" not "0" or "1".
=> icebox: Fix LUT output code.

icetime/icetime.cc
Makes `-d HX1K` work as well as `-d hx1k`.
=> icetime: Lowercase the device type information.

icebox/icebox_asc2hlc.py, icebox/icebox_hlc2asc.py
As mentioned in ca6b2d9ebd521ecec58b9b5627c9380355adeab1, the `routing` switches are not bidirectional. This change removes the changes which supported them as bidirectional.
It also changes the `routing` switch to use `~>` rather than `<->` to be less confusing.
=> Remove bidir stuff in HLC

icebox/icebox_hlc2asc.py
Patch originally created by @jhol.
Examples;
```hlc
lutff_5 {
local_g3_4 -> lutff_5/in_0
local_g0_6 -> lutff_5/in_1
local_g2_7 -> lutff_5/in_2
lutff_5/out -> span4_x3_g12_11
lutff_5/out -> local_g3_5 -> lutff_5/in_3
out = 16'b0111111110000000
enable_dff
}
```
```hlc
lutff_4 {
local_g3_5 -> lutff_4/in_2
lutff_4/out -> span12_y12_g6_0
out = 16'b0000000000010000
enable_dff
}
```
```hlc
lutff_2 {
lutff_2/out -> span12_y12_g8_0
lutff_2/out -> span12_x2_g14_0
lutff_2/out -> local_g0_2 -> lutff_2/in_0
out = 2'b01
enable_dff
}
```
=> icebox_hlc2asc: Allow truth tables to be specified as init string.

icetime/icetime.cc
Makes it easier to know where it can't be found.
=> icetime: Output where the chipdb should be found.

icebox/icebox_hlcsort.py
This is done by sorting all the commands inside a block. Doing so makes
it much easier to diff two files.
=> icebox_hlcsort: Adding a tool for canonicalizing HLC files.

icebox/icebox_hlc2asc.py
Allows for device to specify the package, but select internals just by device class (e.g 1k-tq144 -> 1k)
Add messages to parse errors
=> icebox_hcl2asc: select device class

icebox/icebox_vlog.py
Previously you would end up with an error;
`iceram_bit.v:1889: error: reg n26; cannot be driven by primitives or continuous assignment.`
=> icebox_vlog: Fix constant LUT output.

icebox/icebox_hlc2asc.py
Every other source inside an IO tile supports the `io_X` prefix.
=> Fix spelling and io_X/GLOBAL_OUTPUT_NETWORK

icebox/icebox_vlog.py
Makes it much easier to understand why a net is multi-driver.
Previously if you were doing; `icebox_vlog example.asc > example_bit.v` you would just get;
```
Traceback (most recent call last):
File "icebox_vlog.py", line 947, in <module>
assert False
AssertionError
```
Now you get;
```
Traceback (most recent call last):
File "icebox_vlog.py", line 948, in <module>
assert False, "\n  ".join(emsg)
AssertionError: Single-driver-check failed for 2 nets:
n10 has 0 drivers: []
n15 has 2 drivers: ['clk', 'clk2']
```
=> icebox_vlog: Better information about drivers for nets.

icebox/icebox_hlc2asc.py
'self.lut_bits is None' was always false as it is set to 16*[0]. The _lut_ keyword is used by asc2hlc, so when converting asc->hlc->asc the lut_bits were all zeros.
=> icebox_hlc2asc: fix _lut_ keyword parsing

icebox/icebox.py, icebox/icebox_hlc2asc.py
Adding a new HLC notation to allow tracking of symbols to ASC and therefore back to verilog for debugging final implementation.
=> hlc: parse '.sym>' to track signal names from HLC to ASC

icetime/Makefile, icetime/icetime.cc, icetime/iceutil.cc
Like yosys and arachne-pnr, allow for searching for the desired chipdb file relative to the executing binaries directory. This allows for portable builds of icetime without needing to specify the exact path to the needed chipdb file with the -C arg.
With this change and verbose output, icetime will search like so:
```
// Reading input .asc file..
// Reading 8k chipdb file..
Looking for chipdb '8k' at /usr/local/share/icebox/chipdb-8k.txt
Looking for chipdb '8k' at /home/nathan/dev/fpga/icestorm/icetime/../share/icebox/chipdb-8k.txt
...
```
and with PREFIX having "~/.local/usr":
```
// Reading input .asc file..
// Reading 8k chipdb file..
Looking for chipdb '8k' at /home/nathan/.local/usr/icebox/chipdb-8k.txt
Looking for chipdb '8k' at ~/.local/usr/share/icebox/chipdb-8k.txt
Looking for …
```
=> icetime: Add support for searching for chipdb relative to binary

docs/index.html
Found out the dependencie for boost wasn't complete for Fedora
=> add boost dependencie for fedora

iceprog/iceprog.c
In my setup in OSX I have problems reading from the flash chip but not writing to it and in case of a reading problem iceprog exits and leaves the reset active.
I don't have time to track the issue but I thought it would be no harm to have an option to skip the verification process.
=> Add -X option to iceprog

icetime/icetime.cc
```
icetime.cc: In member function ‘double TimingAnalysis::report(std::__cxx11::string)’:
icetime.cc:1095:15: warning: ‘last_time’ may be used uninitialized in this function [-Wmaybe-uninitialized]
fprintf(frpt, "%10.3f ns ..%7.3f ns %s\n", first_time, last_time, last_net.c_str());
~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
icetime.cc:1095:15: warning: ‘first_time’ may be used uninitialized in this function [-Wmaybe-uninitialized]
```
The variables are not actually being used uninitialized.
Just silence the compiler warning.
=> Fix warnings: 'may be used uninitialized in this function'

icepack/icepack.cc
This is required for some experiments, such as evaluating the SRAM-based BRAM for their properties as a "Physical Unclonable Function" (PUF). In our case this is used for educational purposes, where we try to get away from the vendor software, which supports this feature.
Per default icepack initializes the BRAM with all 0.
Let me know on any doubts you might have.
=> Option for icepack to skip initializing BRAM (tested for ice40hx8k) with "-n"

icepll/icepll.cc
In quiet mode do not print information about the target file.
This way we can really be quiet when writing to a file.
That avoids cluttering project's build logs with redundant information, for example.
=> icepll: In quiet mode don't print info about target file name

icepll/icepll.cc
before:
```
$ ./icepll -q -f /foo
Segmentation fault
```
after:
```
$ ./icepll -q -f /foo
Error: Failed to open output file '/foo': Permission denied
```
=> icepll: Avoid segmentation fault, if opening of output file fails

icebox/icebox.py, icebox/icebox_asc2hlc.py, icebox/icebox_colbuf.py, icebox/icebox_diff.py, icebox/icebox_explain.py, icebox/icebox_hlc2asc.py, icebox/icebox_html.py, icebox/icebox_maps.py, icebox/icebox_stat.py, icebox/icebox_vlog.py
These changes reduce the icebox build time by using LRU caches for often called functions.
The over all (single core) build time is reduced by approximately 16%.
The resulting chipdb*.txt files do not change.
=> Reduce icebox build time

iceprog/iceprog.c
Flashing on windows from stdin or reading back to stdout is currently failing on windows because stdin and stdout are treated as text and occurences of CRLF are converted to LF. This can be fixed by setting stdin/stdout to binary mode.
=> Fix piping on windows

iceprog/iceprog.c
If the flash was in a 'weird' mode (like CRM, QPI, ...), sending
a continuous stream of 0xff should take it out of it.
It looks like the previous code was trying to do that, but
was only transferring 8 bits and then 2 bits which is way
too short.
Signed-off-by: Sylvain Munaut <tnt@246tNt.com>
=> iceprog: Better reset of flash

icetime/iceutil.cc
Clang warns that "adding 'int' to a string does not append to the string".
Although a false positive it's trivially avoided by using the array index
equivalent &PREFIX[1].
=> icetime: avoid string + int Clang warning

config.mk
This attempts to solve the same problem as #240, but is a much better approach. `-MP` causes the compiler to emit dummy targets for every included header file, so that Make won't throw an error if a header disappears. Instead, it will (as it should) simply rebuild the affected files. These dummy targets are ignored in the presence of real targets for e.g. generated headers.
(Sorry if it seems like I'm fighting for a weirdly specific hill. It's just that I remembered about `-MP` while working on an unrelated project and was instantly reminded of #240.)
=> Use -MP to eliminate one way that -MD can fatally confuse make

icetime/icetime.cc
This is triggered for example when icetime is invoked with an empty design.
=> Fix array out of bounds access bug

icebram/icebram.cc
The direct cause of this PR is WASI support. WASI doesn't have `getpid`. However, it does have `getrandom`, so using that is an alternative.
That being said, the discovery that `icebram` will produce nondeterministic result was an unexpected one for me, and relying on PID specifically seems to be the worst of both options: it breaks reproducible builds, but also it does not guarantee unique values, since PIDs can roll over and it doesn't take very long.
I would prefer to have deterministic `icebram`, so I went with that option in the PR.
=> Make icebram deterministic

icebox/icebox.py
This allows selection of the div-by-5 mode of the PLL.
This bit can't be fuzzed because it's not supported by the lattice
tools at all ...
It's only been tested on the UP5k, the other positions are educated
guesses. TBH it might not even exist on older FPGA variants HX/LP ...
Signed-off-by: Sylvain Munaut <tnt@246tNt.com>
=> icebox: Add support for the bit 1 of SHIFTREG_DIV_MODE

iceprog/iceprog.c
This patch adds progress indication for flash writing and reading.
I did not add it to the sram writing as that is pretty quick.
For large payloads progress indication is very important. Especially when the flash is used for more data than just bitstreams and we are writing megabytes of data into the flash.
=> iceprog: Add write and read progress indication.

config.mk, icebox/Makefile, icefuzz/Makefile, icetime/Makefile
The `python` binary can have different names on different platforms.  On Windows, the Python interpreter is called `python` in both the official python.org and Conda binaries.
Use `$(PYTHON)` to call the interpreter in various Makefiles.  This enables `icestorm` to be built on Windows, and as a result enables Windows pacakges in Conda.
=> Use $(PYTHON) in Makefiles instead of `python3`

iceprog/iceprog.c
Fixed a typo in an `iceprog` error message.
=> [iceprog] Fixed typo in error message: "Ignorig"

docs/format.html
The Lattice tools use these additional commands to read-back the BRAM
and CRAM after programming to validate that it was written correctly.
`iceprog` doesn't use this right now, so this is just for documentation
purposes.
Signed-off-by: Trammell Hudson <hudson@trmm.net>
=> docs/format.html: document bram/cram read-back commands

iceprog/iceprog.c
There will be exception when read_size less than 100, read_size / 100 = 0, this generates a div 0 error.
```C
addr / (read_size / 100)
```
=> Fix float exception when value is less than 100

icebram/icebram.cc
When `icebram` is called to replace RAM contents but no RAM contents are replaced, it currently simply exits. This indicates a build failure. (Why else would anyone call `icebram`?)
This becomes more important due to [this issue](https://github.com/YosysHQ/icestorm/issues/301), where `icebram` fails after switching to a new `memory_libmap`. Existing projects that used to build just fine are currently creating broken bitstreams, and unless the `-v` flag is used, no warnings are generated. (Not that anyone actually looks at warnings...)
Ultimately, `icebram` should be fixed so that it works with the new `memory_libmap`, but until that's done, it should at least exit with any error instead, which is what this PR does.
=> Exit with error when no RAM contents were replaced.

docs/io_tile.html, icebox/icebox.py
Only tested on UP5k. For others, it was just deduced.
Signed-off-by: Sylvain Munaut <tnt@246tNt.com>
=> icebox: Add PLL ICEGATE function

icebram/icebram.cc
cc @smunaut 
I've removed the use of exceptions. In one case there's no change but in others it actually improves user experience because there was no `try` block in main and so errors in parsing hex files would look like this:
```
Can't parse line 1 of x.hex: 7d*
terminate called after throwing an instance of 'std::runtime_error'
what():  Invalid input file
Aborted
```
After this PR, it looks like:
```
Can't parse line 1 of x.hex: 7d*
```
=> icebram: fix WebAssembly compatibility

icetime/iceutil.cc
Tweak the FreeBSD version of proc_self_dirname() to work on NetBSD and use it.
Resolves issue #323.
=> Add NetBSD support

examples/icemulti/Makefile, examples/up5k_rgb/rgb.pcf
Hi,
This fixes some errors in the examples/ pojects. In the [Debian packaging of icestorm](https://salsa.debian.org/electronics-team/fpga-icestorm) we build the examples as part of test-suite so failures there hold up releasing new versions.
Thanks,
--Daniel
=> Some fixes for examples/ used by Debian packaging 
